// if (!session)
//     return (
//       <div
//         className="study-material-s"
//         style={{
//           display: "flex",
//           justifyContent: "center",
//           alignItems: "center",
//           height: "100vh",
//           textAlign: "center",
//           backgroundImage: `linear-gradient(rgba(5, 22, 78, 0.7), rgba(90, 4, 69, 0.8)), url(${bg})`,
//           backgroundRepeat: "no-repeat",
//           backgroundSize: "cover",
//           backgroundPosition: "center",
//         }}
//       >
//         <button onClick={() => navigate("/")} className="btn">
//           Sign In to gain access
//         </button>
//       </div>
//     );